export const AUDIO_CONFIG = {
  player: {
    footstepIntervalSeconds: 0.38,
    bumpThrottleSeconds: 0.4,
    servoVolume: 0.85,
    terrainStepVolume: 0.6,
    ambienceVolume: 0.28,
    terrainType: 'field',
    ambienceTrack: 'day',
    aimAssistBaseFrequency: 220,
    aimAssistMaxFrequency: 960,
    aimAssistGain: 0.09,
    aimAssistLockThresholdRadians: 0.05,
    aimAssistUpdateLerp: 0.12,
    sonarActiveDurationSeconds: 0.28,
    environmentalSonarIntervalSeconds: 1.25,
    environmentalSonarEchoDelayPerUnit: 0.026,
    environmentalSonarMaxEchoDistance: 14,
    boundaryWarningDistance: 6,
    boundaryWarningIntervalFarSeconds: 0.95,
    boundaryWarningIntervalNearSeconds: 0.16,
    passiveRadarMinIntervalSeconds: 1.0,
    passiveRadarMaxIntervalSeconds: 3.0,
    passiveRadarEchoGain: 0.12
  },
  enemy: {
    maxDistance: 72,
    baseVolume: 0.9,
    idleFadeSeconds: 0.2,
    movementFadeSeconds: 0.15,
    attackDucking: 0.9,
    attackDuckingSeconds: 0.2,
    passivePingMinMs: 1000,
    passivePingMaxMs: 3000,
    threatCueDelayMs: 360,
    dopplerCentsMin: -250,
    dopplerCentsMax: 250,
    altitudePitchScale: 0.014,
    altitudeFilterScale: 50,
    turnCueThresholdRadians: 0.08,
    turnCueCooldownSeconds: 0.2
  },
  tank: {
    type: 'tank',
    category: 'ground',
    height: 0,
    baseVolume: 0.85,
    passivePingRateMs: 1650,
    movementVariance: 0.14,
    threatCueDelayMs: 360
  },
  helicopter: {
    type: 'helicopter',
    category: 'air',
    height: 2.8,
    baseVolume: 1.15,
    passivePingRateMs: 1200,
    movementVariance: 0.2,
    threatCueDelayMs: 320
  }
} as const

export const AUDIO_NAVIGATION_CONFIG = {
  worldUnitsPerTile: 1,
  playerRadius: 0.5,
  nearFieldRadius: 1.5,
  movementAwarenessRadius: 8,
  obstacleAudioMaxDistance: 12,
  enemyAudioMaxDistance: 40,
  enemyAudioDistanceExponent: 0.9,
  activePingObstacleDistance: 12,
  activePingEnemyDistance: 20,
  passiveSweepTickRateHz: 30,
  passiveSweepRotationSeconds: 2.5,
  sonarSilenceDistance: 10,
  maxSimultaneousObstacleTones: 5,
  losTickIntervalSeconds: 0.3,
  sweepBaseFrequency: 240,
  sweepPitchSpan: 70,
  // Mid-range radar: enemies beyond near exclusion but within radar range
  radarDetectionRange: 80,
  radarNearExclusionRange: 26,
    radarPitchFar: 180,
    radarPitchNear: 520,
  radarTremoloMin: 0.4,
  radarTremoloMax: 7.0,
    radarGain: 2.5,
    destinationToneFarFrequency: 260,
    destinationToneNearFrequency: 980,
    destinationToneRange: 320,
    destinationToneGain: 0.16
} as const
