export const CANVAS_WIDTH_LIMIT = 1280
export const CANVAS_HEIGHT_LIMIT = 1024
export const CANVAS_VERTICAL_MARGIN = 40
export const FOV = Math.PI / 3
export const HALF_FOV = FOV / 2
export const MAX_DEPTH = 64
export const MAP_WIDTH = 48
export const MAP_HEIGHT = 48
export const PLAYER_HEIGHT = 0.5
export const PLAYER_SPEED = 3.0
export const TURN_SPEED = 1.8
export const LOOK_SPEED = 1.5
export const MAX_LOOK_PITCH = 0.7
export const PLAYER_RADIUS = 0.25
export const FOOTSTEP_INTERVAL_SECONDS = 0.38
export const BULLET_SPEED = 40
export const BULLET_MAX_DIST = 48
export const MUZZLE_FLASH_DURATION = 0.1
export const TANK_SPEED = 1.2
export const TANK_CANNON_RANGE = 20
export const TANK_CANNON_FIRE_INTERVAL = 2000
export const TANK_THREAT_DELAY_MS = 360
export const TANK_HEALTH = 30
export const TANK_PROJECTILE_SPEED = 30
